/*
  ___   _   _   ___   _   _ _____ ___   _   __
 / _ \ | \ | | / _ \ | \ | |_   _/ _ \ | | / /
/ /_\ \|  \| |/ /_\ \|  \| | | |/ /_\ \| |/ / 
|  _  || . ` ||  _  || . ` | | ||  _  ||    \ 
| | | || |\  || | | || |\  | | || | | || |\  \
\_| |_/\_| \_/\_| |_/\_| \_/ \_/\_| |_/\_| \_/
                                                                       
Project PROGENY main.cpp
Initial file automatically generated by PROGENY on 04/18/23 12:42:56
*/

#include "main.h" // include header
#include "PROGENY.h" // include the default library

// include libs I commonly use
#include "stdio.h"
#include "stdlib.h"
#include <errno.h> // Error integer and strerror() function
#include <unistd.h> // write(), read(), close()
#include <fcntl.h> // Contains file controls like O_RDWR

#include <string>
#include <limits.h>
#include <chrono>
#include "stdbool.h"
#include <iostream>

// less common libs
//#include "linux/serial.h" // Serial comms
//#include "linux/can.h" // CAN bus comms
//#include "seanComm.h"
//#include "joystick.h" // joystick style controls
//#include <iomanip>
//#include <chrono>
//#include <thread>
//#include <mutex>
//#include "sys/socket.h" // bare TCP
//#include "mosquitto.h" // mqtt


using namespace std; // default namespace

int main(int argc, char *argv[]){

	cout << "Hello world" << endl;


	while(true){



	}
}





