/*
    ____  __  _______________________            _____    _   __________    ______
   / __ )/ / / / ___/_  __/ ____/ __ \          / /   |  / | / / ____/ /   / ____/
  / __  / / / /\__ \ / / / __/ / /_/ /_______  / / /| | /  |/ / / __/ /   / __/
 / /_/ / /_/ /___/ // / / /___/ _, _/_____/ /_/ / ___ |/ /|  / /_/ / /___/ /___
/_____/\____//____//_/ /_____/_/ |_|      \____/_/  |_/_/ |_/\____/_____/_____/

Project PROGENY_PROJECT_NAME main.cpp
Initial file automatically generated by PROGENY on PROGENY_CURRENT_DATE
*/

#include "main.h" // include main header
#include "PROGENY_PROJECT_NAME.h" // include the default library

// include common headers by default
#include "stdio.h"
#include "stdlib.h"
#include <errno.h> // Error integer and strerror() function
#include <unistd.h> // write(), read(), close()
#include <fcntl.h> // Contains file controls like O_RDWR
#include <string>
#include <limits.h>
#include <chrono>
#include "stdbool.h"
#include <iostream>
#include <thread>
#include <mutex>
#include "plog/Log.h"
#include "plog/Initializers/RollingFileInitializer.h"
#include "plog/Initializers/ConsoleInitializer.h"
#include "CLI/App.hpp"
#include "CLI/Validators.hpp"
#include "CLI/Formatter.hpp"
#include "CLI/Config.hpp"
#include <ftxui/component/component.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/dom/elements.hpp>

using namespace ftxui;
using namespace std; // default namespace

struct LogLevelValidator : public CLI::Validator {
    LogLevelValidator() {
        name_ = "severity";
        func_ = [](const std::string &str) {

            if(!(str == "NONE" || str == "VERB" || str == "DEBUG" || str == "INFO" || str == "WARN" || str == "ERROR" || str == "FATAL"))
                return std::string("Specified logging severity level is not an accepted string. You gave: " + str);
            else
                return std::string();
        };
    }
};
const static LogLevelValidator WarningLevel;

std::string getApplicationVersionInfo() {
    char buf[512];
    snprintf(buf, sizeof(buf),
        "Project:    %s\n"
        "Branch:     %s\n"
        "Commit:     %s%s\n"
        "Build Type: %s\n"
        "Build Date: %s\n"
        "Build Host: %s\n",
        PROJECT_NAME,
        GIT_BRANCH,
        GIT_HASH, GIT_DIRTY ? " (dirty)" : "",
        BUILD_TYPE,
        BUILD_DATE,
        BUILD_HOST
    );
    return std::string(buf);
}

int main(int argc, char *argv[]){
    ////Set CLI defaults
    std::string logfilePath = "/var/logs//PROGENY_PROJECT_NAME/PROGENY_PROJECT_NAME.log"; // Default logfile path
    std::string logSeverityInputStr = "WARN"; // default severity level of application-level logging
    bool printVersion = false;
    ///// Configure and parse CLI options
    CLI::App cli{"-PROGENY_PROJECT_NAME application description-"};
    cli.add_option("-l,--logfile", logfilePath, "Logfile destination. Default: ./logs/PROGENY_PROJECT_NAME.log");
    cli.add_option("-s,--severity", logSeverityInputStr, "Logging minimum severity threshold. Default: INFO. Acceptable values:\n\tNONE (Dont log)\n\tVERB\n\tDEBUG\n\tINFO\n\tWARN\n\tERROR\n\tFATAL")->check(WarningLevel);
    cli.add_flag("-v,--version", printVersion, "Print version information");

    CLI11_PARSE(cli, argc, argv);
    if(printVersion){ // Print version information and exit
        cout << getApplicationVersionInfo();
        return EXIT_SUCCESS;
    }

    static plog::RollingFileAppender<plog::CsvFormatter> fileAppender(logfilePath.c_str(), 1048576, 3); // Create the file appender, up to 1MB per file, rolling over 3 files
    static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender; // Create the console appender
    plog::Severity applicationLogSeverity = plog::severityFromString(logSeverityInputStr.c_str()); // stringify the log severity level from console input
    plog::init(applicationLogSeverity, &fileAppender).addAppender(&consoleAppender); // Initialize the logger with the both appenders.

    PLOGI << "Started logging.";
    PLOGD.printf("Printf style debug msg");

    PROGENY_PROJECT_NAME object;
    PROGENY_PROJECT_NAME object2;
    object.init(plog::warning, plog::get()); // Initialize a library with a PLOG appender, but only log warning (or higher) level messages.
    object2.init(plog::verbose, plog::get()); // Initialize a library with a PLOG appender, and log verbose messages.


    object.multiply(1, 2);
    object2.multiply(1, 2);


    printf("\033[2J\033[H"); // clear screen, move cursor to top-left

    // --- Static DOM example ---
    // Build a simple layout with a border and some styled text
    auto document = vbox({
        text("FTXUI Basic Example") | bold | color(Color::Green) | hcenter,
        separator(),
        hbox({
            text(" Status: ") | bold,
            text("Running") | color(Color::Cyan),
        }),
        hbox({
            text(" Build:  ") | bold,
            text("Release") | color(Color::Yellow),
        }),
        separator(),
        text("Press [q] to quit") | dim | hcenter,
    }) | border;

    // --- Interactive example ---
    auto screen = ScreenInteractive::TerminalOutput();

    // A simple menu
    std::vector<std::string> menu_items = { "Option A", "Option B", "Option C", "Quit" };
    int selected = 0;

    auto menu = Menu(&menu_items, &selected);

    // Wrap in a renderer to combine the static DOM with the interactive menu
    auto renderer = Renderer(menu, [&] {
        return vbox({
            document,
            separator(),
            text("Select an option:") | bold,
            menu->Render() | border,
        });
    });

    // Handle input
    auto root = CatchEvent(renderer, [&](Event event) {
        if (event == Event::Character('q') ||
            (event == Event::Return && selected == (int)menu_items.size() - 1)) {
            screen.ExitLoopClosure()();
            return true;
        }
        return false;
    });

    screen.Loop(root);
    return EXIT_SUCCESS;
}





