/*
  ___   _   _   ___   _   _ _____ ___   _   __
 / _ \ | \ | | / _ \ | \ | |_   _/ _ \ | | / /
/ /_\ \|  \| |/ /_\ \|  \| | | |/ /_\ \| |/ /
|  _  || . ` ||  _  || . ` | | ||  _  ||    \
| | | || |\  || | | || |\  | | || | | || |\  \
\_| |_/\_| \_/\_| |_/\_| \_/ \_/\_| |_/\_| \_/

Project $PROJECT_NAME main.cpp
Initial file automatically generated by PROGENY on 04/18/23 12:42:56
*/

#include "test.h" // include main header
#include "PROGENY_PROJECT_NAME.h" // include the default library

// include common headers by default
#include "stdio.h"
#include "stdlib.h"
#include <errno.h> // Error integer and strerror() function
#include <unistd.h> // write(), read(), close()
#include <fcntl.h> // Contains file controls like O_RDWR
#include <string>
#include <limits.h>
#include <chrono>
#include "stdbool.h"
#include <iostream>
#include <thread>
#include <mutex>
#include <plog/Log.h>
#include "plog/Initializers/RollingFileInitializer.h"

using namespace std; // default namespace

int main(int argc, char *argv[]){
    plog::init(plog::info, "test_default.log"); // Step2: initialize the logger

    PLOG_INFO << "Starting test.";

    bool testStatus = true;

    if(!testStatus){
        PLOG_ERROR << "Test Failed";
        return EXIT_FAILURE;
    }

    PLOG_INFO << "Test Passed";
    return EXIT_SUCCESS;
}