name: Build And Release

on:
  push:
    branches:
      - release  # or specify your desired branch here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake  # Install CMake using apt-get

      - name: Install Ninja build
        run: |
          sudo apt-get install -y ninja-build

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: ninja

      - name: Test
        run: ctest

      - name: Generate artifacts
        run: ninja package package_source #Build the project with Ninja, and generate a binary package, plus a sourcecode package

